# Generated by Django 2.2.24 on 2023-07-13 17:45

from django.db import migrations
import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        try:
            phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(phonenumber):
                formatted_number = phonenumbers.format_number(phonenumber, phonenumbers.PhoneNumberFormat.E164)
            else:
                formatted_number = None
        except (phonenumbers.NumberParseException, AttributeError):
            continue
        flat.owner_pure_phone = formatted_number
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber, move_backward)
    ]
