# Generated by Django 2.2.24 on 2023-07-13 17:45

from django.db import migrations
import phonenumbers


def normalize_phonenumber(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            formatted_number = phonenumbers.format_number(phonenumber, phonenumbers.PhoneNumberFormat.E164)
        except (phonenumbers.NumberParseException, AttributeError):
            formatted_number = None
        flat.owner_pure_phone = formatted_number
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumber)
    ]
